# Generated by Django 5.1.4 on 2025-01-20 05:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0005_patient_bmi_patient_bmr_patient_calories_need_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dietitian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(default=0)),
                ("gender", models.CharField(default="", max_length=8)),
                ("qualifications", models.TextField(blank=True, default="", null=True)),
                ("years_of_experience", models.IntegerField(default=0)),
                (
                    "specialties",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "bio",
                    models.CharField(blank=True, default="", max_length=300, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg", upload_to="dietitian_pictures/"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=15, null=True),
                ),
                ("dob", models.DateTimeField(default=datetime.datetime.now)),
                ("availability", models.JSONField(default=dict)),
                ("consultation_fee", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "reason_for_visit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, default="", null=True)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.patient"
                    ),
                ),
                (
                    "dietitian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dietitian.dietitian",
                    ),
                ),
            ],
            options={
                "ordering": ["appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientDietitianRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=datetime.datetime.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="", null=True)),
                (
                    "dietitian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dietitian.dietitian",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.patient"
                    ),
                ),
            ],
        ),
    ]
