# Generated by Django 5.1.4 on 2025-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dietitian", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietitian",
            name="availability",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
