# Generated by Django 5.1.4 on 2025-01-20 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Dietitian", "0002_alter_dietitian_availability"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientDietitianRelation",
        ),
    ]
