# Generated by Django 5.1.4 on 2025-01-17 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="workoutRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sat_work", models.CharField(default="", max_length=10)),
                ("sun_work", models.CharField(default="", max_length=10)),
                ("mon_work", models.CharField(default="", max_length=10)),
                ("tue_work", models.CharField(default="", max_length=10)),
                ("wed_work", models.CharField(default="", max_length=10)),
                ("thu_work", models.CharField(default="", max_length=10)),
                ("fri_work", models.CharField(default="", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
