# Generated by Django 5.1.4 on 2025-01-17 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_workoutroutine_fri_time_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutroutine",
            name="fri_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="fri_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="mon_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="mon_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="sat_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="sat_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="sun_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="sun_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="thu_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="thu_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="tue_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="tue_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="wed_time_end",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="wed_time_start",
            field=models.TimeField(default=datetime.time(12, 0), null=True),
        ),
    ]
