# Generated by Django 5.1.4 on 2025-01-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0005_alter_event_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
