# Generated by Django 5.1.4 on 2025-01-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0006_event_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutroutine",
            name="fri_work",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="mon_work",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="sat_work",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="sun_work",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="thu_work",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="tue_work",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AlterField(
            model_name="workoutroutine",
            name="wed_work",
            field=models.CharField(default="No", max_length=10),
        ),
    ]
