# Generated by Django 5.1.4 on 2024-12-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(default=0)),
                ("gender", models.CharField(default="", max_length=8)),
                ("height", models.FloatField(default=0.0)),
                ("weight", models.FloatField(default=0.0)),
                ("activity_level", models.CharField(default="", max_length=20)),
                ("bio", models.CharField(default="", max_length=200)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pc"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
