# Generated by Django 5.1.4 on 2024-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
        ),
    ]
