# Generated by Django 5.1.4 on 2024-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_patient_location_patient_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="profile_pictures/"
            ),
        ),
    ]
