# Generated by Django 5.1.4 on 2024-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_patient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="activity_level",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
    ]
