# Generated by Django 5.1.4 on 2024-12-09 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_patient_activity_level_alter_patient_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="bmi",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="patient",
            name="bmr",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="patient",
            name="calories_need",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="patient",
            name="activity_level",
            field=models.FloatField(default=0.0),
        ),
    ]
